### ISSUE TITLE
Missing ./configuration-interfaces/validator-config.d

### ISSUE THREAD

**Issue by MPBatista** [YStrauch/swagger-object-validator#1]
In the last release v1.1.0, it's missing for me the following file in the lib folder, after a NPM INSTALL:
node_modules/swagger-object-validator/lib/handler.d.ts(3,34): error TS2307: Cannot find module './configuration-interfaces/validator-config.d'. 

After adding the following file by hand, everything is alright.

Could you help us with this issue?

**Comment by YStrauch** [comment]
Sorry for the missing file - I added it to the plugin in V1.1.1
