### ISSUE TITLE
Schema not defined in "definitions"

### ISSUE THREAD

**Issue by ultimatelife** [YStrauch/swagger-object-validator#10]
Validation did not occur like following case not defined in `definitions`.
```
  /person:
    post:
      summary: sample
      operationId: Person
      parameters:
        - name: Person
          in: body
          required: true
          schema:
            properties:
              name:
                type: string
                minLength: 2
                maxLength: 5
            required:
              - name
      responses:
        200:
          description: ok
```

**Comment by YStrauch** [comment]
Hi!
Apologies for this late response.
This was always possible since the `validateModel`-function allowed you to pass anonymous model specs from anywhere. I've added documentation, please find it https://github.com/YStrauch/swagger-object-validator#inline-models
