### ISSUE TITLE
DateValidator, fullTime validation-missing Z,z,-,+ causing unexpected error ('Cannot read property "length" of undefined')

### ISSUE THREAD

**Issue by stavavram** [YStrauch/swagger-object-validator#13]

**Comment by stavavram** [comment]
I tried to use the validator in order to failed wrong datetime by not sending 'Z' at the end.
I got unexpected  error instead of clear error message:
'Cannot read property "length" of undefined'

In my case, the client might send any wrong date to the validator and expect to get clear message about wrong date format

**Comment by YStrauch** [comment]
Hello!

Thanks for letting me know. I have corrected the issue in V1.2.1

Best regards
