### ISSUE TITLE
Update promise implementation to native node.js from bluebird

### ISSUE THREAD

**Issue by ZehuaZhang** [YStrauch/swagger-object-validator#19]
I saw promises are implement from `bluebird`, instead of native `node.js`

Is there any future plan for improving that?

**Comment by YStrauch** [comment]
The choice of bluebird was deliberate as its performance and memory footprint is better than the native implementation, see i.e. https://blog.kuzzle.io/bluebird-native-async_await-javascript-promises-performances-2020
