### ISSUE TITLE
Not validating number

### ISSUE THREAD

**Issue by MPBatista** [YStrauch/swagger-object-validator#2]
When we use:

type: number
format: float

And try the number:

-1234.58

It returns a:

"Type mismatch:"

Is it correct?

**Comment by YStrauch** [comment]
I fixed the error - negative floats were wrongly recognised as doubles. Fixed in V1.1.2

**Comment by MPBatista** [comment]
Chahinaz,

Je n'ai pas les statutaire dans mon agenda. Est-ce que tu peux me 
rajouter, stp?

Cordialement,
Mateus Pereira Batista
Architecte de solution - Consultant
Service des Technologies de l'Information

800 boulevard de Maisonneuve Est, Suite 301A
Montréal (Québec)
Tél.:  514 833-4358
xbatima@ville.montreal.qc.ca




De :    YStrauch <notifications@github.com>
A :     YStrauch/swagger-object-validator 
<swagger-object-validator@noreply.github.com>
Cc :    Mateus Pereira Batista <xbatima@ville.montreal.qc.ca>, Author 
<author@noreply.github.com>
Date :  2017-05-24 17:40
Objet : Re: [YStrauch/swagger-object-validator] Not validating number (#2)



Closed #2.
