### ISSUE TITLE
internal logic should have converted relative paths to absolute (1.4.3)

### ISSUE THREAD

**Issue by samw2k00** [YStrauch/swagger-object-validator#35]
after upgrading to 1.4.3 we are getting the following issue instead

node_modules/swagger-object-validator/lib/helpers/loader.js:98
            throw Error('Non-absolute path found, internal logic should have converted relative paths to absolute');

**Comment by YStrauch** [comment]
I've validated your previous piece of code and it works, can you provide a minimal working example?

**Comment by samw2k00** [comment]
Thank you, i found out basically no longer support the relative path. I have to provide the full path of JSON if I want to use the one locally.

**Comment by YStrauch** [comment]
This is not intended behaviour, changing to absolute paths will indeed hide that bug so that your part works again but this issue needs to be addressed.

#36 Has the same issue so I leave this report closed in favour to the other one
