### ISSUE TITLE
Clarify it only validates definitions

### ISSUE THREAD

**Issue by elgalu** [YStrauch/swagger-object-validator#4]
Hi, thanks for this library, is quite cool.

It would be nice if it could be clarified, in the README, that this library only validates definitions, not paths and not JSON full responses, for instance.

I'm looking for a full JSON response validation per path, please let me know if you know of something like that.

**Comment by YStrauch** [comment]
Hi!

This is exactly what you look for! Please read the README.md for examples on how to validate your JSON responses.
