### ISSUE TITLE
es5-compatible release?

### ISSUE THREAD

**Issue by matt-deboer** [YStrauch/swagger-object-validator#5]
First, thanks for your work -- this library was just what I needed.
Unfortunately, the current es6 release cannot be handled by uglify-js (used by current create-react-app), and thus it fails the build. Any chance you could publish an es5-transpiled version to npm?

**Comment by YStrauch** [comment]
Frontend validation was not the main purpose of the plugin (why documented in #3), but I will see what I can do for you.

**Comment by matt-deboer** [comment]
Thanks much!
