### ISSUE TITLE
custom ignoreError function causes another error to be thrown

### ISSUE THREAD

**Issue by ethanchiddicks** [YStrauch/swagger-object-validator#9]
Related to #8 

As a workaround for the above issue, I added an ignoreError function to ignore cases where non-required fields were set to null.

Example (ES6):
```
var swaggerValidator = require('swagger-object-validator');
var validator = new swaggerValidator.Handler('https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/yaml/petstore.yaml',
  {
    allowAdditionalProperties: true,
    ignoreError: (error, value, schema, spec) => {
      // Set Ignore cases where non-required fields are set to null rather than specified type/format
      return error.errorType === swaggerValidator.ValidationErrorType.TYPE_MISMATCH &&
        !spec.definitions[error.trace[0].stepName].required.includes(error.trace[1].stepName) &&
        value === null;
    }
  });

var pet = {
  id: 3942394023,
  name: 'Pippin',
  tag: null
}

validator.validateModel(pet, 'Pet', function (err, result) {
  console.log(err);
});
```

However, rather than ignoring the error as I expected, it throws the following Error:

> Type string not yet implemented (in undefined)

Thrown from at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
Originating (I think) from lib/validators/ModelValidator.js at line 53

**Comment by YStrauch** [comment]
Hi!

Sorry for the late reply.
I've checked your code sample and it works for me without problems.
As the documentation says, ignoring errors can produce these effects, i.e. if I set the complete pet to null.

I will close this ticket as the code is working and documentation already states that this is an experimental feature.
